moonstuff/urls.py
from django.urls import re_path

from . import views

app_name = "moonstuff"

urlpatterns = [
    re_path(r'^$', views.dashboard, name='dashboard'),
    re_path(r'^scan/$', views.add_scan, name='add_scan'),
    re_path(r'^track/$', views.add_character, name='add_character'),
    re_path(r'^info/(?P<moon_id>[0-9]+)/$', views.moon_info, name='view_moon')
]

moonstuff/models.py
from django.db import models
from datetime import timedelta


from allianceauth.eveonline.models import EveCharacter, EveCorporationInfo
from eveuniverse.models import EveMoon, EveType


# Create your models here.
class Moonstuff(models.Model):

    class Meta:
        managed = False
        default_permissions = (())
        permissions = (
            ('access_moonstuff', 'Allows access to the moonstuff module'),
            ('access_moon_list', 'Allows access to list of all moons.'),
        )


class Resource(models.Model):
    ore = models.ForeignKey(EveType, on_delete=models.CASCADE)
    quantity = models.DecimalField(max_digits=11, decimal_places=10)
    moon = models.ForeignKey(EveMoon, on_delete=models.CASCADE, related_name='resources')

    @property
    def rarity(self):
        """
        Determine the rarity of the resource by its group_id. (Default is 0)
        :return:
        """
        rs = {1884: 4, 1920: 8, 1921: 16, 1922: 32, 1923: 64}
        return rs.get(self.ore.eve_group_id, 0)

    def __str__(self):
        return f"{self.ore.name} x {self.quantity} ({self.moon.name})"

    class Meta:
        default_permissions = ('add',)


class Refinery(models.Model):
    structure_id = models.BigIntegerField(primary_key=True)
    evetype = models.ForeignKey(EveType, on_delete=models.CASCADE)
    name = models.CharField(null=True, max_length=255)  # Might not actually need this.
    corp = models.ForeignKey(EveCorporationInfo, on_delete=models.CASCADE, related_name='refineries')
    observer = models.BooleanField(default=True)

    def __str__(self):
        if self.name is None:
            return f'Unknown Structure ID{self.structure_id} ({self.evetype.name})'
        return f'{self.name}'

    class Meta:
        default_permissions = (())
        verbose_name_plural = "Refineries"


class TrackingCharacter(models.Model):
    character = models.OneToOneField(EveCharacter, on_delete=models.CASCADE)
    latest_notification_id = models.BigIntegerField(null=True, default=0)
    last_notification_check = models.DateTimeField(null=True)

    def __str__(self):
        return f'{self.character.character_name}'

    class Meta:
        default_permissions = ('add',)


class Extraction(models.Model):
    start_time = models.DateTimeField()
    arrival_time = models.DateTimeField()
    decay_time = models.DateTimeField()
    moon = models.ForeignKey(EveMoon, on_delete=models.CASCADE, related_name='extractions')
    refinery = models.ForeignKey(Refinery, on_delete=models.CASCADE, related_name='extractions')
    corp = models.ForeignKey(EveCorporationInfo, on_delete=models.CASCADE, related_name='extractions')
    cancelled = models.BooleanField(null=False, default=False)
    jackpot = models.BooleanField(default=False)
    active = models.BooleanField(default=False)
    depleted = models.BooleanField(default=False)
    total_volume = models.BigIntegerField(null=True)

    @property
    def despawn(self):
        """
        Returns the latest despawn time. Actual despawn can be up to -3h from returned time depending on when the
            moon drill laser was fired. Actual despawn should never occur after returned time however.
        :return:
        """
        return self.decay_time + timedelta(hours=48)

    class Meta:
        default_permissions = (())
        unique_together = (('start_time', 'moon'),)


class LedgerEntry(models.Model):
    observer = models.ForeignKey(Refinery, on_delete=models.CASCADE, related_name='entries')
    character_id = models.IntegerField()  # There is no guarantee that we will have a character object for this.
    last_updated = models.DateField()
    quantity = models.BigIntegerField()
    recorded_corporation_id = models.IntegerField()
    evetype = models.ForeignKey(EveType, on_delete=models.CASCADE, related_name='ledger_entries')

    class Meta:
        default_permissions = (())
        # For each observer we only want one record per day per character per ore type.
        unique_together = (('observer', 'last_updated', 'character_id', 'evetype'),)

moonstuff/templates/moonstuff/add_scan.html
{% extends 'moonstuff/base.html' %}
{% load i18n %}

{% block moon_title %} {% translate 'Add Scan' %} {% endblock %}

{% block moon_block %}
    <div class="container-fluid">
        <div class="panel panel-primary">
            <div class="panel-heading"> {% translate "Moon Scan Input" %} </div>
            <div class="panel-body">
                <form role="form" method="post" action="">
                    {% csrf_token %}
                    <div class="form-group">
                        <textarea class="form-control" name="scan" id="scanBox" rows="10" cols="15" required aria-required="true"></textarea>
                    </div>
                    <br />
                    <button type="submit" role="button" class="btn btn-block btn-primary" name="submit_scan" id="submit_scan">
                        {% translate "Submit Moon Scan(s)" %}
                    </button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

moonstuff/templates/moonstuff/base.html
{% extends 'allianceauth/base-bs5.html' %}
{% load i18n %}

{% block page_title %}{% block moon_title %}{% endblock %} - {% translate "Moonstuff" %}{% endblock %}

{% block header_nav_brand %}
    {% translate "Moonstuff" %}
{% endblock %}

{% block header_nav_collapse_left %}
         {% if perms.moonstuff.add_trackingcharacter %}
             <li class="nav-item">
                 <a class="nav-link" href="{% url 'moonstuff:add_character' %}">{# <i class="fa-solid fa-users-rays"></i> #} {% translate "Add Tracking Character" %}</a>
             </li>
             <li class="nav-item">
                 <a class="nav-link" href="{% url 'moonstuff:add_scan' %}">{# <i class="fa-solid fa-satellite-dish"></i> #}{% translate "Add Moon Scan" %}</a>
             </li>
        {% endif %}
{% endblock %}

{% block content %}
    <div class="col-lg-12" style="padding: 0 !important;">
        <br />
        <div class="col-lg-12 container-fluid">
            {% block moon_block %}{% endblock %}
        </div>
    </div>
{% endblock %}

moonstuff/templates/moonstuff/moon_info.html
{% extends 'moonstuff/base.html' %}
{% load i18n %}
{% load evelinks %}

{% block moon_title %} {% translate 'Moon Info' %} - {{ moon.name }} {% endblock %}

{% block moon_block %}
    {% include 'moonstuff/moon_info_ajax.html' %}
{% endblock %}

{% block extra_javascript %}
    {% include 'bundles/datatables-js.html' %}
    {% include 'bundles/moment-js.html' %}
{% endblock %}

{% block extra_css %}
    <link rel="stylesheet" href="/static/moonstuff/css/style.css">
    {% include 'bundles/datatables-css.html' %}
{% endblock %}

<script>
    {% block extra_script %}
        $(function() {
                $('#pastTable').DataTable({
                    'bFilter': false,
                    "sScrollY": "220px",
                    "bPaginate": false
                });
            });
    {% endblock %}
</script>

moonstuff/templates/moonstuff/moon_info_ajax.html
{% load i18n %}
{% load humanize %}
{% load evelinks %}

<div>
    <h2><span id="title">{{ moon.name }}</span></h2>

    <br />

    <div class="col-md-12" id="content" >
        <div class="row">
            <div class="col-md-5">
                <div class="card card-info">
                    <div class="card-heading">Resources</div>
                    <div class="card-body">
                        {% for res in moon.resources.all|order_quantity %}
                            <img src="{{ res.ore.id|type_icon_url:32 }}" /> {{ res.ore.name }} <span class="badge bg-R{{ res.rarity }}">R{{ res.rarity }}</span> <i style="font-size: 80% !important;">{{ resources|get_item:res.ore.id|floatformat:2|intcomma }} isk/m<sup>3</sup></i>
                            <div class="progress" style="margin-left: 0;">
                                <div class="progress-bar progress-bar-danger progress-bar-striped" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width: {{ res.quantity|percent }}%;">
                                    <h5 class="media-heading percent">{{ res.quantity|percent }}% </h5>
                                </div>
                            </div>
                            <br />
                        {% endfor %}
                    </div>
                </div>
            </div>
            <div class="col-md-7">
                <div class="card card-default">
                    <div class="card-heading">Extractions</div>
                    <div class="card-body">
                        <table class="table table-striped" id="pastTable">
                            <thead>
                                <th>Date</th>
                                <th>Jackpot?</th>
                            </thead>
                            <tbody>
                                {% for ext in moon.extractions.all.reverse%}
                                    <tr>
                                        <td>{{ ext.arrival_time|date:"Y-n-j H:i" }}</td>
                                        <td>
                                            {% if ext.jackpot %}
                                                <span class="fas fa-check"></span>
                                            {% else %}
                                                <span class="fas fa-times"></span>
                                            {% endif %}
                                        </td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>